import { createClient } from "@supabase/supabase-js";

const supabase = createClient(
  Deno.env.get("NEXT_PUBLIC_SUPABASE_URL") ?? "",
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? ""
);

async function createWorkflowNotification(
  tenantId: string,
  title: string,
  body: string,
  channel = "in_app"
) {
  await supabase.from("notifications").insert({
    tenant_id: tenantId,
    channel,
    title,
    body,
    status: "pending"
  });
}

async function executeStepAction(instance: {
  id: string;
  tenant_id: string;
  entity_id: string;
  entity_type: string;
  state_json: unknown;
}, step: Record<string, unknown>) {
  const stepName =
    (typeof step.step === "string" ? step.step : null) ??
    (typeof step.action === "string" ? step.action : null) ??
    "unknown";
  const state = ((instance.state_json as Record<string, unknown> | null) ?? {});

  if (stepName === "validate_order") {
    return {
      orderValidated: true
    };
  }

  if (stepName === "reserve_capacity") {
    await supabase.from("work_orders").insert({
      tenant_id: instance.tenant_id,
      order_id:
        instance.entity_type === "order" ? instance.entity_id : null,
      type: "capacity_reservation",
      status: "open",
      notes: `Generated by workflow ${instance.id} during reserve_capacity.`
    });

    return {
      capacityReserved: true
    };
  }

  if (stepName === "notify_customer" || stepName === "send_customer_advisory") {
    await createWorkflowNotification(
      instance.tenant_id,
      "Customer advisory",
      `Workflow ${instance.id} executed step ${stepName} for ${instance.entity_type} ${instance.entity_id}.`
    );

    return {
      customerNotified: true
    };
  }

  if (stepName === "page_field_team") {
    await createWorkflowNotification(
      instance.tenant_id,
      "Field team dispatch",
      `Workflow ${instance.id} requires field action for ${instance.entity_type} ${instance.entity_id}.`
    );

    const smsTarget = Deno.env.get("FAULT_ONCALL_SMS");
    if (smsTarget) {
      await createWorkflowNotification(
        instance.tenant_id,
        "Field team dispatch",
        `Workflow ${instance.id} requires field action for ${instance.entity_type} ${instance.entity_id}.`,
        "sms"
      );
    }

    return {
      fieldTeamPaged: true
    };
  }

  if (stepName === "create_ticket") {
    let existingTicketQuery = supabase
      .from("trouble_tickets")
      .select("id, ticket_number")
      .eq("tenant_id", instance.tenant_id)
      .eq("status", "open");

    if (instance.entity_type === "service") {
      existingTicketQuery = existingTicketQuery.eq(
        "service_instance_id",
        instance.entity_id
      );
    }

    const { data: existingTicket } = await existingTicketQuery.maybeSingle();

    if (existingTicket) {
      return {
        ticketCreated: existingTicket.ticket_number
      };
    }

    const alarmId =
      instance.entity_type === "alarm"
        ? instance.entity_id
        : typeof state.alarmId === "string"
          ? state.alarmId
          : null;

    const { data: alarm } = alarmId
      ? await supabase
          .from("alarms")
          .select("network_element_id, severity, description")
          .eq("id", alarmId)
          .maybeSingle()
      : { data: null };

    const ticketNumber = `TT-${Date.now()}`;
    const { data: ticket, error: ticketError } = await supabase
      .from("trouble_tickets")
      .insert({
        tenant_id: instance.tenant_id,
        ticket_number: ticketNumber,
        title: `Workflow-generated ticket for ${instance.entity_type}`,
        description:
          alarm?.description ??
          `Generated by workflow ${instance.id} for ${instance.entity_type} ${instance.entity_id}.`,
        severity: alarm?.severity ?? "major",
        status: "open",
        network_element_id: alarm?.network_element_id ?? null,
        service_instance_id: instance.entity_type === "service" ? instance.entity_id : null
      })
      .select("id, ticket_number")
      .single();

    if (ticketError || !ticket) {
      throw new Error(ticketError?.message ?? "Unable to create workflow ticket.");
    }

    await supabase.from("event_log").insert({
      tenant_id: instance.tenant_id,
      event_type: "ticket.created",
      entity_type: "trouble_ticket",
      entity_id: ticket.id,
      payload_json: ticket,
      source_service: "workflow-engine"
    });

    return {
      ticketCreated: ticket.ticket_number
    };
  }

  if (stepName === "provision" || stepName === "provision_service") {
    const serviceInstanceId =
      instance.entity_type === "service"
        ? instance.entity_id
        : typeof state.serviceInstanceId === "string"
          ? state.serviceInstanceId
          : null;

    if (serviceInstanceId) {
      await supabase
        .from("service_instances")
        .update({
          status: "active",
          activated_at: new Date().toISOString()
        })
        .eq("id", serviceInstanceId);
    }

    return {
      serviceProvisioned: Boolean(serviceInstanceId)
    };
  }

  if (stepName === "approve_reconciliation") {
    const reconciliationId =
      instance.entity_type === "reconciliation"
        ? instance.entity_id
        : typeof state.reconciliationId === "string"
          ? state.reconciliationId
          : null;

    if (reconciliationId) {
      await supabase
        .from("reconciliation_runs")
        .update({
          status: "approved",
          approved_at: new Date().toISOString()
        })
        .eq("id", reconciliationId);
    }

    return {
      reconciliationApproved: Boolean(reconciliationId)
    };
  }

  return {
    lastAction: stepName
  };
}

Deno.serve(async (request) => {
  const body = await request.json().catch(() => ({}));
  const workflowInstanceId = body.workflowInstanceId as string | undefined;

  if (!workflowInstanceId) {
    return Response.json({ error: "workflowInstanceId is required." }, { status: 400 });
  }

  const { data: instance, error: instanceError } = await supabase
    .from("workflow_instances")
    .select("id, tenant_id, workflow_id, current_step, status, state_json, workflows(steps_json)")
    .eq("id", workflowInstanceId)
    .maybeSingle();

  if (instanceError || !instance) {
    return Response.json({ error: instanceError?.message ?? "Workflow instance not found." }, { status: 404 });
  }

  const steps = ((instance.workflows as { steps_json?: unknown } | null)?.steps_json as Array<Record<string, unknown>> | undefined) ?? [];
  const nextStepIndex = Number(instance.current_step ?? 0);

  if (nextStepIndex >= steps.length) {
    await supabase
      .from("workflow_instances")
      .update({
        status: "completed",
        completed_at: new Date().toISOString()
      })
      .eq("id", workflowInstanceId);

    return Response.json({ completed: true });
  }

  const step = steps[nextStepIndex];
  const stepResult = await executeStepAction(instance, step ?? {});
  const newState = {
    ...((instance.state_json as Record<string, unknown> | null) ?? {}),
    ...stepResult,
    last_step: step,
    last_step_executed_at: new Date().toISOString()
  };

  await supabase
    .from("workflow_instances")
    .update({
      current_step: nextStepIndex + 1,
      state_json: newState,
      status: nextStepIndex + 1 >= steps.length ? "completed" : "running",
      completed_at: nextStepIndex + 1 >= steps.length ? new Date().toISOString() : null
    })
    .eq("id", workflowInstanceId);

  await supabase.from("event_log").insert({
    tenant_id: instance.tenant_id,
    event_type: "workflow.step.executed",
    entity_type: "workflow_instance",
    entity_id: instance.id,
    payload_json: {
      step,
      stepResult,
      currentStep: nextStepIndex + 1
    },
    source_service: "workflow-engine"
  });

  return Response.json({
    completed: nextStepIndex + 1 >= steps.length,
    currentStep: nextStepIndex + 1,
    step,
    stepResult
  });
});
